name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python packages
        run: pip install -r calculator/requirements.txt
        
      - name: Start the REST API
        run: python calculator/calculator.py --rest &
        
      - name: Run tests with pytest
        run: pytest --junit-xml=report.xml
        
      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: judevops.azurecr.io
          username: '${{ secrets.ACR_USERNAME }}'
          password: '${{ secrets.ACR_PASSWORD }}'
          
      - name: Build and Push Docker Image
        run: |
          docker build . --file dockerfile --tag judevops.azurecr.io/abdulrahman_mofleh-calculater:${{github.run_number }}
          docker push judevops.azurecr.io/abdulrahman_mofleh-calculater:${{github.run_number }}
        if: ${{ success() }}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'report.xml'
